version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  webapp:
    depends_on:
      postgres : 
        condition: service_healthy
    build: ./
    image: webapp
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    command: uvicorn webapp.application:app --host 0.0.0.0 --port 8000 --reload
